# Generated by Django 2.1.2 on 2018-10-30 16:59

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('bbs_exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wysiwyg',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('wysiwyg_field', django_summernote.fields.SummernoteTextField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbs_exp.Wysiwyg'),
        ),
    ]
