# Generated by Django 2.1.2 on 2018-10-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_exp', '0002_auto_20181031_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='context',
        ),
        migrations.AddField(
            model_name='wysiwyg',
            name='post',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bbs_exp.Post'),
        ),
    ]
