# Generated by Django 2.1.2 on 2018-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_exp', '0003_auto_20181031_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(default='Writer', max_length=15),
        ),
    ]
