# Generated by Django 2.1.2 on 2018-11-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs_exp', '0004_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
