# Generated by Django 2.1.2 on 2018-11-17 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Job Name', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 6, 8, 43, 587716, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='job',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login_example.Job'),
        ),
    ]
