# Generated by Django 2.1.2 on 2018-11-17 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_example', '0002_auto_20181117_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 6, 29, 22, 124641, tzinfo=utc)),
        ),
    ]
