# Generated by Django 2.1.2 on 2018-11-17 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_example', '0003_auto_20181117_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 12, 12, 42, 71707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_example.Job'),
        ),
    ]
