# Generated by Django 2.1.2 on 2018-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Non Name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Non Title', max_length=100)),
                ('singer', models.CharField(default='Various', max_length=20)),
                ('year', models.IntegerField(default=1900)),
            ],
        ),
    ]
