# Generated by Django 2.1.2 on 2018-10-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music_example.Genre'),
        ),
    ]
